/**
 * Colour schemes: what is persisted, and that the list has one home.
 *
 * The palettes themselves are generated by `scripts/gen-themes.py` and measured
 * by `scripts/audit-contrast.py`, which is the gate that decides whether a
 * scheme is legible. What is left for a unit test is the wiring — whether a
 * choice survives, whether junk in storage can put the app into a scheme that
 * does not exist, and whether the menu and the stylesheet still agree about
 * what the schemes are.
 *
 * That last one is the same failure the model allow-list had: two lists, drift
 * in either direction, and both directions silent. A scheme in the CSS that the
 * menu never offers is unreachable; one in the menu with no CSS behind it is a
 * click that changes nothing at all.
 */
import { execFileSync } from 'node:child_process'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'

const store = new Map<string, string>()

beforeEach(() => {
  store.clear()
  vi.stubGlobal('localStorage', {
    getItem: (k: string) => store.get(k) ?? null,
    setItem: (k: string, v: string) => void store.set(k, v),
  })
})

afterEach(() => {
  vi.unstubAllGlobals()
  vi.resetModules()
})

describe('scheme persistence', () => {
  it('round-trips through localStorage', async () => {
    const { loadScheme, saveScheme } = await import('../src/web/lib/prefs.ts')
    expect(loadScheme()).toBe('graphite')
    saveScheme('ember')
    expect(loadScheme()).toBe('ember')
  })

  /*
   * localStorage: a palette is a statement about the person and the room they
   * are in, and should outlive the tab. The fleet filter is kept there too, so
   * that a view chosen once does not have to be chosen again every morning.
   */
  it('is remembered across tabs, which is what localStorage means', async () => {
    const { saveScheme } = await import('../src/web/lib/prefs.ts')
    saveScheme('solar')
    vi.resetModules()
    const fresh = await import('../src/web/lib/prefs.ts')
    expect(fresh.loadScheme()).toBe('solar')
  })

  it('falls back to the default for a value that is not a scheme', async () => {
    const { loadScheme } = await import('../src/web/lib/prefs.ts')
    store.set('agent-commander.scheme', 'chartreuse')
    expect(loadScheme()).toBe('graphite')
  })

  it('survives storage that throws', async () => {
    vi.stubGlobal('localStorage', {
      getItem: () => {
        throw new Error('Safari private mode')
      },
      setItem: () => {
        throw new Error('Safari private mode')
      },
    })
    const { loadScheme, saveScheme } = await import('../src/web/lib/prefs.ts')
    // A preference that cannot be stored is a preference that does not stick.
    // It is not a reason for the app not to start.
    expect(() => saveScheme('mauve')).not.toThrow()
    expect(loadScheme()).toBe('graphite')
  })

  it('accepts every scheme the menu can actually set', async () => {
    const { SCHEMES, loadScheme, saveScheme } = await import('../src/web/lib/prefs.ts')
    for (const scheme of SCHEMES) {
      saveScheme(scheme)
      expect(loadScheme()).toBe(scheme)
    }
  })
})

describe('the schemes in the menu are the schemes in the stylesheet', () => {
  const css = readFileSync(resolve('src/web/styles/tokens.css'), 'utf8')

  it('every scheme offered has a palette behind it', async () => {
    const { SCHEMES, DEFAULT_SCHEME } = await import('../src/web/lib/prefs.ts')
    for (const scheme of SCHEMES) {
      if (scheme === DEFAULT_SCHEME) continue
      expect(css, scheme).toContain(`[data-scheme='${scheme}']`)
    }
  })

  it('every palette in the stylesheet is offered', async () => {
    const { SCHEMES } = await import('../src/web/lib/prefs.ts')
    const inCss = new Set([...css.matchAll(/\[data-scheme='([a-z0-9-]+)'\]/g)].map((m) => m[1]))
    for (const scheme of inCss) {
      expect(SCHEMES as readonly string[], scheme).toContain(scheme)
    }
  })

  /*
   * The settings menu draws all five schemes at once, inside a document that is
   * only ever in one of them — so it cannot read their tokens, which are
   * defined on `:root[data-scheme=…]` and match the root element alone. The
   * generator emits a separate `--swatch-*` set for exactly this, and a missing
   * one is a swatch that silently falls back to `transparent`: a blank pill
   * that looks like a rendering glitch rather than a missing variable.
   */
  it('every scheme has swatch colours the menu can reach', async () => {
    const { SCHEMES } = await import('../src/web/lib/prefs.ts')
    for (const scheme of SCHEMES) {
      for (const token of ['bg', 'panel-2', 'accent']) {
        expect(css, `${scheme}/${token}`).toContain(`--swatch-${scheme}-${token}:`)
      }
    }
  })

  // The default is the bare `:root`, which is what makes a document with no
  // attributes at all a complete theme rather than an unstyled one.
  it('the default scheme sets no attribute of its own', async () => {
    const { DEFAULT_SCHEME } = await import('../src/web/lib/prefs.ts')
    expect(css).not.toContain(`[data-scheme='${DEFAULT_SCHEME}']`)
  })

  it('every palette defines the whole token set', () => {
    // A scheme missing a token does not fail loudly: it inherits whatever the
    // previous scheme left in `:root`, so one colour from another palette turns
    // up in the middle of this one.
    const required = [
      'bg', 'panel', 'panel-2', 'line', 'line-strong',
      'text', 'dim', 'faint',
      'busy', 'waiting', 'idle', 'accent', 'danger', 'focus', 'shadow',
    ]
    const blocks = [...css.matchAll(/(:root[^{]*)\{([^{}]*)\}/g)].filter(([, , body]) =>
      (body as string).includes('--bg:'),
    )
    expect(blocks.length).toBeGreaterThanOrEqual(10)
    for (const [, selector, body] of blocks) {
      for (const token of required) {
        expect(body, `${(selector as string).trim()} is missing --${token}`).toContain(`--${token}:`)
      }
    }
  })
})

describe('the generated stylesheet is the generator output', () => {
  /*
   * `tokens.css` says GENERATED at the top, and a file that says that is a file
   * someone will eventually edit anyway — to nudge one colour, in a hurry. The
   * edit survives until the next `--write`, which then reverts it silently.
   *
   * Regenerating and comparing makes that a failed test rather than a mystery.
   * It is also the only thing tying the reasoning in `gen-themes.py` to the
   * values the app actually ships: without it the generator could drift into
   * being documentation of a decision nobody is making any more.
   */
  it('re-running the generator reproduces the file byte for byte', () => {
    const generated = execFileSync('python3', ['scripts/gen-themes.py'], {
      encoding: 'utf8',
      timeout: 60_000,
    })
    const onDisk = readFileSync(resolve('src/web/styles/tokens.css'), 'utf8')
    expect(
      generated === onDisk
        ? true
        : 'tokens.css differs from the generator: run `python3 scripts/gen-themes.py --write`',
    ).toBe(true)
  })
})
