// Generated by scripts/gen-ui-icons.py -- do not edit.
//
//     python3 scripts/gen-ui-icons.py --write
//
// One grid and one stroke weight for every control face in the app. The shapes
// and the reasoning live in the generator; `test/icons.test.ts` re-runs it and
// fails a checkout where this file has drifted. Rendered by `ui/Icon.tsx`,
// which is the only thing that should import this.
//
// (`gen-icons.py`, without the `ui`, is a different script: it draws the
// application icon. See that file's docstring.)


export const ICON_VIEWBOX = 24
export const ICON_STROKE = 1.7

export const ICON_PATHS = {
  'chevron-right':
    '<path d="M9.5 5.5 16 12l-6.5 6.5"/>',
  'chevron-down':
    '<path d="M5.5 9.5 12 16l6.5-6.5"/>',
  'ellipsis':
    '<circle cx="5.2" cy="12" r="1.35"/><circle cx="12" cy="12" r="1.35"/><circle cx="18.8" cy="12" r="1.35"/>',
  'expand':
    '<path d="M14 4h6v6M20 4l-7.2 7.2M10 20H4v-6M4 20l7.2-7.2"/>',
  'panel-hide':
    '<path d="M20 4.5v15M15.5 12H5M9.2 7.8 5 12l4.2 4.2"/>',
  'panel-show':
    '<path d="M4 4.5v15M8.5 12H19M14.8 7.8 19 12l-4.2 4.2"/>',
  'arrow-up':
    '<path d="M12 19.5V5M6.2 10.8 12 5l5.8 5.8"/>',
  'arrow-down':
    '<path d="M12 4.5V19M6.2 13.2 12 19l5.8-5.8"/>',
  'arrow-right':
    '<path d="M4.5 12h15M13.7 6.2 19.5 12l-5.8 5.8"/>',
  'check':
    '<path d="M5 12.8 9.4 17.2 19 6.6"/>',
  'close':
    '<path d="M6.2 6.2 17.8 17.8M17.8 6.2 6.2 17.8"/>',
  'stop':
    '<rect x="6.4" y="6.4" width="11.2" height="11.2" rx="2.4"/>',
  'gear':
    '<circle cx="12" cy="12" r="3.1"/><path d="M12 3.4v2.3M12 18.3v2.3M20.6 12h-2.3M5.7 12H3.4M18.08 5.92l-1.63 1.63M7.55 16.45l-1.63 1.63M18.08 18.08l-1.63-1.63M7.55 7.55 5.92 5.92"/>',
  'help':
    '<circle cx="12" cy="12" r="8.4"/><path d="M9.6 9.6a2.5 2.5 0 1 1 3.4 2.33c-.78.32-1 .84-1 1.57M12 16.9v.1"/>',
  'bell':
    '<path d="M12 3.6a5 5 0 0 0-5 5v3.4L5.4 15.2v1.1h13.2v-1.1L17 12V8.6a5 5 0 0 0-5-5Z"/><path d="M9.7 18.9a2.4 2.4 0 0 0 4.6 0"/>',
  'bell-off':
    '<path d="M12 3.6a5 5 0 0 0-5 5v3.4L5.4 15.2v1.1h13.2v-1.1L17 12V8.6a5 5 0 0 0-5-5Z"/><path d="M9.7 18.9a2.4 2.4 0 0 0 4.6 0"/><path d="M4.4 19.6 19.6 4.4"/>',
} as const

export type IconName = keyof typeof ICON_PATHS
