// Generated by scripts/gen-ui-icons.py -- do not edit.
//
//     python3 scripts/gen-ui-icons.py --write
//
// One grid and one stroke weight for every control face in the app. The shapes
// and the reasoning live in the generator; `test/icons.test.ts` re-runs it and
// fails a checkout where this file has drifted. Rendered by `ui/Icon.tsx`,
// which is the only thing that should import this.
//
// (`gen-icons.py`, without the `ui`, is a different script: it draws the
// application icon. See that file's docstring.)


export const ICON_VIEWBOX = 24
export const ICON_STROKE = 2.1

export const ICON_PATHS = {
  'chevron-right':
    '<path d="M9 5L16 12L9 19"/>',
  'chevron-down':
    '<path d="M5 9L12 16L19 9"/>',
  'ellipsis':
    '<circle cx="5" cy="12" r="1"/><circle cx="12" cy="12" r="1"/><circle cx="19" cy="12" r="1"/>',
  'expand':
    '<path d="M9 4.5H4.5V9"/><path d="M15 4.5H19.5V9"/><path d="M15 19.5H19.5V15"/><path d="M9 19.5H4.5V15"/>',
  'panel-hide':
    '<path d="M5.5 4.5V19.5"/><path d="M16 6.5L11 12L16 17.5"/>',
  'panel-show':
    '<path d="M18.5 4.5V19.5"/><path d="M8 6.5L13 12L8 17.5"/>',
  'arrow-up':
    '<path d="M12 19V5"/><path d="M6 11L12 5L18 11"/>',
  'arrow-down':
    '<path d="M12 5V19"/><path d="M6 13L12 19L18 13"/>',
  'arrow-right':
    '<path d="M5 12H19"/><path d="M13 6L19 12L13 18"/>',
  'check':
    '<path d="M5 12.5L9.5 17L19 6.5"/>',
  'close':
    '<path d="M6 6L18 18"/><path d="M18 6L6 18"/>',
  'stop':
    '<rect x="5.5" y="5.5" width="13" height="13" rx="2.5"/>',
  'gear':
    '<circle cx="12" cy="12" r="5.2"/><line x1="17.2" y1="12" x2="20.6" y2="12"/><line x1="14.6" y1="16.5" x2="16.3" y2="19.4"/><line x1="9.4" y1="16.5" x2="7.7" y2="19.4"/><line x1="6.8" y1="12" x2="3.4" y2="12"/><line x1="9.4" y1="7.5" x2="7.7" y2="4.6"/><line x1="14.6" y1="7.5" x2="16.3" y2="4.6"/>',
  'help':
    '<path d="M8.6 9.6A3.8 3.8 0 1 1 12 12.4V13.9"/><circle cx="12" cy="18.6" r="1"/>',
  'bell':
    '<path d="M6.2 15.4H17.8V10.6A5.8 5.8 0 0 0 6.2 10.6Z"/><path d="M10.3 19.4H13.7"/>',
  'bell-off':
    '<path d="M6.2 15.4H17.8V10.6A5.8 5.8 0 0 0 6.2 10.6Z"/><path d="M3.6 20.4L20.4 3.6"/>',
  'hand':
    '<path d="M9.6 12.6V6.4a2.5 2.5 0 0 1 5 0v6M14.6 12.4V8a2.5 2.5 0 0 1 5 0v7.6a5.2 5.2 0 0 1-5.2 5.2h-1.6a5.2 5.2 0 0 1-5.2-5.2v-3a2 2 0 0 0-4 0"/>',
  'ring':
    '<circle cx="12" cy="12" r="7.6"/>',
  'arc':
    '<circle cx="12" cy="12" r="7.6" opacity="0.28"/><path d="M12 4.4A7.6 7.6 0 0 1 19.6 12"/>',
  'ring-off':
    '<circle cx="12" cy="12" r="7.6"/><path d="M6.2 17.8L17.8 6.2"/>',
  'screen':
    '<rect x="3.2" y="4.6" width="17.6" height="12.4" rx="2.4"/><path d="M9 20.4H15"/>',
  'screen-off':
    '<rect x="3.2" y="4.6" width="17.6" height="12.4" rx="2.4"/><path d="M9 20.4H15"/><path d="M3.4 19.6L20.6 4.4"/>',
  'picture':
    '<rect x="3.6" y="4.6" width="16.8" height="14.8" rx="2.4"/><path d="M4.4 16.4L9.6 10.6L14.4 15.4"/><circle cx="15.6" cy="9.2" r="1.2"/>',
} as const

export type IconName = keyof typeof ICON_PATHS
