/**
 * Theme, language and fleet-filter preferences.
 *
 * Theme is applied as a `data-theme` attribute on <html> rather than by
 * swapping stylesheets, so the CSS can express all three states: an explicit
 * light or dark choice, and "system", which falls through to the media query.
 */
import { detectLang, isLang, type Lang } from './i18n.ts'
import { GROUPS } from './format.ts'
import { SORTS, type SortDir, type SortKey, type StatusFilter } from './filter.ts'

export const THEMES = ['system', 'light', 'dark'] as const
export type Theme = (typeof THEMES)[number]

/**
 * Colour schemes, in the order the menu offers them.
 *
 * Separate from `Theme` on purpose: a scheme is which palette family, and the
 * theme is light or dark *within* it. Folding them into one list would mean ten
 * entries in a menu and no way to say "this one, but follow the system".
 *
 * The values are generated by `scripts/gen-themes.py` and measured by
 * `scripts/audit-contrast.py`; this list only has to name them. `graphite` is
 * the default and is written as the bare `:root`, so it sets no attribute at
 * all — which is also what makes a document with no attributes complete.
 */
export const SCHEMES = ['graphite', 'nordic', 'solar', 'ember', 'mauve'] as const
export type Scheme = (typeof SCHEMES)[number]

export const DEFAULT_SCHEME: Scheme = 'graphite'

const THEME_KEY = 'agent-commander.theme'
const SCHEME_KEY = 'agent-commander.scheme'
const LANG_KEY = 'agent-commander.lang'
const FILTER_KEY = 'agent-commander.filter'
const SORT_KEY = 'agent-commander.sort'
const DIR_KEY = 'agent-commander.dir'

function isTheme(value: unknown): value is Theme {
  return typeof value === 'string' && (THEMES as readonly string[]).includes(value)
}

function isScheme(value: unknown): value is Scheme {
  return typeof value === 'string' && (SCHEMES as readonly string[]).includes(value)
}

function read(key: string): string | null {
  try {
    return localStorage.getItem(key)
  } catch {
    // Safari private mode throws on localStorage; preferences just won't stick.
    return null
  }
}

function write(key: string, value: string): void {
  try {
    localStorage.setItem(key, value)
  } catch {
    /* not fatal */
  }
}

/*
 * The fleet view — status filter, sort key, sort direction — persists in
 * localStorage, alongside theme and language, so it survives quitting the
 * browser rather than only a reload.
 *
 * This was sessionStorage, on the reasoning that a filter is a statement about
 * the task in front of you rather than about you, and that a tab opened next
 * week should not silently show only "needs you" for a reason days in the past.
 * The objection is about *silently*, and the chip answers it: the active filter
 * is a header control carrying a glyph as well as a fill, precisely so that
 * arriving at an already-filtered dashboard reads as a filter rather than as an
 * empty fleet. What was actually being paid for that safety was retyping the
 * same choice every morning.
 *
 * The three move together on purpose. "Least tokens first, idle only" is one
 * thought, and restoring the filter while resetting the sort put the user back
 * in a view they never chose — arguably worse than resetting all three, since
 * the half that survived makes the half that did not look deliberate. That is
 * why this moved as a set: persisting only the filter would recreate exactly
 * that split.
 */

const FILTERS: readonly StatusFilter[] = ['all', ...GROUPS.map((g) => g.key)]

function isFilter(value: unknown): value is StatusFilter {
  return typeof value === 'string' && (FILTERS as readonly string[]).includes(value)
}

export function loadFilter(): StatusFilter {
  const stored = read(FILTER_KEY)
  return isFilter(stored) ? stored : 'all'
}

export function saveFilter(filter: StatusFilter): void {
  write(FILTER_KEY, filter)
}

function isSort(value: unknown): value is SortKey {
  return typeof value === 'string' && (SORTS as readonly string[]).includes(value)
}

function isDir(value: unknown): value is SortDir {
  return value === 'asc' || value === 'desc'
}

export function loadSort(): SortKey {
  const stored = read(SORT_KEY)
  return isSort(stored) ? stored : 'recent'
}

export function saveSort(sort: SortKey): void {
  write(SORT_KEY, sort)
}

export function loadDir(): SortDir {
  const stored = read(DIR_KEY)
  return isDir(stored) ? stored : 'desc'
}

export function saveDir(dir: SortDir): void {
  write(DIR_KEY, dir)
}

export function loadTheme(): Theme {
  const stored = read(THEME_KEY)
  return isTheme(stored) ? stored : 'system'
}

export function saveTheme(theme: Theme): void {
  write(THEME_KEY, theme)
}

export function loadScheme(): Scheme {
  const stored = read(SCHEME_KEY)
  return isScheme(stored) ? stored : DEFAULT_SCHEME
}

export function saveScheme(scheme: Scheme): void {
  write(SCHEME_KEY, scheme)
}

export function loadLang(): Lang {
  const stored = read(LANG_KEY)
  return isLang(stored) ? stored : detectLang()
}

export function saveLang(lang: Lang): void {
  write(LANG_KEY, lang)
}

/** Which palette a theme setting actually resolves to right now. */
export function resolveTheme(theme: Theme): 'light' | 'dark' {
  if (theme !== 'system') return theme
  const dark = typeof matchMedia === 'function' && matchMedia('(prefers-color-scheme: dark)').matches
  return dark ? 'dark' : 'light'
}

/**
 * Apply the theme to the document. "system" removes the attribute entirely so
 * the prefers-color-scheme media query takes over.
 */
export function applyTheme(theme: Theme): void {
  const root = document.documentElement
  if (theme === 'system') root.removeAttribute('data-theme')
  else root.setAttribute('data-theme', theme)
  syncThemeColor()
}

/**
 * Apply the colour scheme. The default sets no attribute, matching the CSS,
 * where it is the bare `:root`.
 */
export function applyScheme(scheme: Scheme): void {
  const root = document.documentElement
  if (scheme === DEFAULT_SCHEME) root.removeAttribute('data-scheme')
  else root.setAttribute('data-scheme', scheme)
  syncThemeColor()
}

/**
 * Keep the iOS status bar in step with whatever is actually on screen.
 *
 * Read back from the document rather than held as a table here. There are ten
 * palettes now, and a second copy of their background colours in TypeScript
 * would be a list to forget to update — the failure being a status bar in one
 * scheme's colour above another scheme's page, which nobody would think to
 * check. `getComputedStyle` asks the only thing that actually knows.
 */
function syncThemeColor(): void {
  const metas = document.querySelectorAll<HTMLMetaElement>('meta[name="theme-color"]')
  if (metas.length === 0) return
  let bg = ''
  try {
    bg = getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()
  } catch {
    // jsdom and some embedded webviews; the status bar is cosmetic, so a
    // failure here must not stop the theme being applied.
  }
  if (!bg) return
  for (const meta of metas) meta.content = bg
}

export function applyLang(lang: Lang): void {
  document.documentElement.lang = lang
}
