/**
 * Theme, language and fleet-filter preferences.
 *
 * Theme is applied as a `data-theme` attribute on <html> rather than by
 * swapping stylesheets, so the CSS can express all three states: an explicit
 * light or dark choice, and "system", which falls through to the media query.
 */
import { detectLang, isLang, type Lang } from './i18n.ts'
import { GROUPS } from './format.ts'
import { SORTS, type SortDir, type SortKey, type StatusFilter } from './filter.ts'
import type { Agent } from '../../shared/types.ts'

export const THEMES = ['system', 'light', 'dark'] as const
export type Theme = (typeof THEMES)[number]

/**
 * Colour schemes, in the order the menu offers them.
 *
 * Separate from `Theme` on purpose: a scheme is which palette family, and the
 * theme is light or dark *within* it. Folding them into one list would mean ten
 * entries in a menu and no way to say "this one, but follow the system".
 *
 * The values are generated by `scripts/gen-themes.py` and measured by
 * `scripts/audit-contrast.py`; this list only has to name them. `graphite` is
 * the default and is written as the bare `:root`, so it sets no attribute at
 * all — which is also what makes a document with no attributes complete.
 */
export const SCHEMES = [
  'graphite',
  'nordic',
  'solar',
  'ember',
  'mauve',
  'one',
  'dracula',
  'monokai',
] as const
export type Scheme = (typeof SCHEMES)[number]

export const DEFAULT_SCHEME: Scheme = 'graphite'

/**
 * Which way the fleet is drawn.
 *
 * `forest` draws every session as a family — an agent with whatever it handed
 * out beneath it — on one shared time axis. `legacy` is the card list the app
 * shipped with, grouped by status.
 *
 * Both are supported and neither is on its way out: this is a choice about how
 * you want to read the fleet, not a migration with a deprecated half. Which one
 * suits depends on the fleet in front of you — a dozen agents that delegate are
 * a forest, and six that do not are a list.
 */
const THEME_KEY = 'agent-commander.theme'
const NOTIFY_KEY = 'agent-commander.notify'
const SCHEME_KEY = 'agent-commander.scheme'
const LANG_KEY = 'agent-commander.lang'
const FILTER_KEY = 'agent-commander.filter'
const SORT_KEY = 'agent-commander.sort'
const DIR_KEY = 'agent-commander.dir'
const TERMINALS_KEY = 'agent-commander.terminals'

function isTheme(value: unknown): value is Theme {
  return typeof value === 'string' && (THEMES as readonly string[]).includes(value)
}

function isScheme(value: unknown): value is Scheme {
  return typeof value === 'string' && (SCHEMES as readonly string[]).includes(value)
}

function read(key: string): string | null {
  try {
    return localStorage.getItem(key)
  } catch {
    // Safari private mode throws on localStorage; preferences just won't stick.
    return null
  }
}

function write(key: string, value: string): void {
  try {
    localStorage.setItem(key, value)
  } catch {
    /* not fatal */
  }
}

/*
 * The fleet view — status filter, sort key, sort direction — persists in
 * localStorage, alongside theme and language, so it survives quitting the
 * browser rather than only a reload.
 *
 * This was sessionStorage, on the reasoning that a filter is a statement about
 * the task in front of you rather than about you, and that a tab opened next
 * week should not silently show only "needs you" for a reason days in the past.
 * The objection is about *silently*, and the chip answers it: the active filter
 * is a header control carrying a glyph as well as a fill, precisely so that
 * arriving at an already-filtered dashboard reads as a filter rather than as an
 * empty fleet. What was actually being paid for that safety was retyping the
 * same choice every morning.
 *
 * The three move together on purpose. "Least tokens first, idle only" is one
 * thought, and restoring the filter while resetting the sort put the user back
 * in a view they never chose — arguably worse than resetting all three, since
 * the half that survived makes the half that did not look deliberate. That is
 * why this moved as a set: persisting only the filter would recreate exactly
 * that split.
 */

const FILTERS: readonly StatusFilter[] = ['all', ...GROUPS.map((g) => g.key)]

function isFilter(value: unknown): value is StatusFilter {
  return typeof value === 'string' && (FILTERS as readonly string[]).includes(value)
}

export function loadFilter(): StatusFilter {
  const stored = read(FILTER_KEY)
  return isFilter(stored) ? stored : 'all'
}

export function saveFilter(filter: StatusFilter): void {
  write(FILTER_KEY, filter)
}

/*
 * Terminals are out of the fleet until asked for, and the ask sticks.
 *
 * Off by default because the fleet answers "which agent needs me" and a shell
 * never does. It persists for the same reason the three above do: someone who
 * keeps a couple of terminals open wants them there every morning, and
 * re-admitting them daily is the friction that made the filter persist in the
 * first place. It is stored separately rather than as a fourth `StatusFilter`
 * because it is orthogonal — a terminal has a status like anything else, and
 * folding the two together would make "busy only" and "with terminals"
 * mutually exclusive.
 */
export type TerminalsChoice = 'on' | 'off'

export function loadTerminals(): TerminalsChoice {
  return read(TERMINALS_KEY) === 'on' ? 'on' : 'off'
}

export function saveTerminals(choice: TerminalsChoice): void {
  write(TERMINALS_KEY, choice)
}

/*
 * Off by default: an OS notification is the app reaching out of its tab, and
 * that is opted into, never inherited. The stored preference is only half the
 * gate — the browser's own permission is checked again at fire time, so
 * revoking it in site settings wins over anything stored here.
 */
export type NotifyChoice = 'on' | 'off'

export function loadNotify(): NotifyChoice {
  return read(NOTIFY_KEY) === 'on' ? 'on' : 'off'
}

export function saveNotify(choice: NotifyChoice): void {
  write(NOTIFY_KEY, choice)
}

/*
 * Whether the one-time nudge — "an agent just needed you, get notified next
 * time?" — has been waved away. Per browser, like the preference it points
 * at, and never asked again once it has: a nudge that keeps coming back is a
 * nag, and this app makes exactly one unsolicited suggestion.
 */
const NUDGE_KEY = 'agent-commander.notify-nudge'

export function loadNudgeDismissed(): boolean {
  return read(NUDGE_KEY) === 'dismissed'
}

export function saveNudgeDismissed(): void {
  write(NUDGE_KEY, 'dismissed')
}

function isSort(value: unknown): value is SortKey {
  return typeof value === 'string' && (SORTS as readonly string[]).includes(value)
}

function isDir(value: unknown): value is SortDir {
  return value === 'asc' || value === 'desc'
}

export function loadSort(): SortKey {
  const stored = read(SORT_KEY)
  return isSort(stored) ? stored : 'recent'
}

export function saveSort(sort: SortKey): void {
  write(SORT_KEY, sort)
}

export function loadDir(): SortDir {
  const stored = read(DIR_KEY)
  return isDir(stored) ? stored : 'desc'
}

export function saveDir(dir: SortDir): void {
  write(DIR_KEY, dir)
}

/**
 * What Send does when the agent is already working.
 *
 * `queue` types the message at the agent and lets it arrive whenever the agent
 * next reads its prompt — what this app has always done. `interrupt` stops the
 * agent first, then sends.
 *
 * Per agent, because it is a judgement about *this* session: an agent grinding
 * through a long sweep is one you interrupt, and one mid-refactor is one you
 * let finish. A single global setting would carry a habit formed on a scratch
 * session onto a run you did not want cut off.
 */
export type SendMode = 'queue' | 'interrupt'

const SEND_MODE_PREFIX = 'agent-commander.send-mode.'

function isSendMode(value: unknown): value is SendMode {
  return value === 'queue' || value === 'interrupt'
}

export function loadSendMode(sessionId: string): SendMode {
  const stored = read(SEND_MODE_PREFIX + sessionId)
  // Queue is the default deliberately: it is what the app did before this
  // existed, and it is the one that cannot destroy work in flight.
  return isSendMode(stored) ? stored : 'queue'
}

export function saveSendMode(sessionId: string, mode: SendMode): void {
  write(SEND_MODE_PREFIX + sessionId, mode)
}

export function loadTheme(): Theme {
  const stored = read(THEME_KEY)
  return isTheme(stored) ? stored : 'system'
}

export function saveTheme(theme: Theme): void {
  write(THEME_KEY, theme)
}

export function loadScheme(): Scheme {
  const stored = read(SCHEME_KEY)
  return isScheme(stored) ? stored : DEFAULT_SCHEME
}

export function saveScheme(scheme: Scheme): void {
  write(SCHEME_KEY, scheme)
}

export function loadLang(): Lang {
  const stored = read(LANG_KEY)
  return isLang(stored) ? stored : detectLang()
}

export function saveLang(lang: Lang): void {
  write(LANG_KEY, lang)
}

/** Which palette a theme setting actually resolves to right now. */
export function resolveTheme(theme: Theme): 'light' | 'dark' {
  if (theme !== 'system') return theme
  const dark = typeof matchMedia === 'function' && matchMedia('(prefers-color-scheme: dark)').matches
  return dark ? 'dark' : 'light'
}

/**
 * Apply the theme to the document. "system" removes the attribute entirely so
 * the prefers-color-scheme media query takes over.
 */
export function applyTheme(theme: Theme): void {
  const root = document.documentElement
  if (theme === 'system') root.removeAttribute('data-theme')
  else root.setAttribute('data-theme', theme)
  syncThemeColor()
}

/**
 * Apply the colour scheme. The default sets no attribute, matching the CSS,
 * where it is the bare `:root`.
 */
export function applyScheme(scheme: Scheme): void {
  const root = document.documentElement
  if (scheme === DEFAULT_SCHEME) root.removeAttribute('data-scheme')
  else root.setAttribute('data-scheme', scheme)
  syncThemeColor()
}

/**
 * Keep the iOS status bar in step with whatever is actually on screen.
 *
 * Read back from the document rather than held as a table here. There are ten
 * palettes now, and a second copy of their background colours in TypeScript
 * would be a list to forget to update — the failure being a status bar in one
 * scheme's colour above another scheme's page, which nobody would think to
 * check. `getComputedStyle` asks the only thing that actually knows.
 */
function syncThemeColor(): void {
  const metas = document.querySelectorAll<HTMLMetaElement>('meta[name="theme-color"]')
  if (metas.length === 0) return
  let bg = ''
  try {
    bg = getComputedStyle(document.documentElement).getPropertyValue('--bg').trim()
  } catch {
    // jsdom and some embedded webviews; the status bar is cosmetic, so a
    // failure here must not stop the theme being applied.
  }
  if (!bg) return
  for (const meta of metas) meta.content = bg
}

export function applyLang(lang: Lang): void {
  document.documentElement.lang = lang
}

/*
 * How wide the fleet column is, and whether it is on screen at all.
 *
 * It used to be `minmax(340px, 430px)`, which resolves to its 430 maximum on
 * any desktop and leaves ~415px of content once `scrollbar-gutter` has taken
 * its share — 21.5% of a 1440x900 viewport spent on the list while reading one
 * agent, measured against the mock fleet.
 *
 * 288 is not a taste: it is Claude Desktop's own `sidebarWidth` default, read
 * out of its bundle, where it sits beside a `collapsed` boolean on a 1200x800
 * default window. That is a 24% column against a 76% conversation, and it is
 * the same shape of thing this column is, so it is the reference rather than a
 * number picked to look right.
 *
 * Collapsing takes the column away rather than shrinking it to icons. An icon
 * rail was built first and rejected: it keeps presence but loses the names the
 * column exists for, and a 56px strip is a third layout to reason about. Gone
 * is one state, honest, and it is what Claude Desktop's own collapse does.
 *
 * Expanded is the default because names are why anyone keeps a fleet column.
 * The trade is stated rather than hidden: expanded measures ~74.4% work
 * surface at 1440x900 against ~97% collapsed, so the 80% bar is something a
 * reader opts out of deliberately, per browser, and it sticks.
 */
export type SidebarState = 'expanded' | 'collapsed'

/** Claude Desktop's own default, and therefore this app's. */
export const SIDEBAR_WIDTH_DEFAULT = 288
/** Under this the names this column exists for ellipsise to nothing. */
export const SIDEBAR_WIDTH_MIN = 200
/**
 * Today's 430px track less its scrollbar gutter. Widening can still reach
 * exactly what the column already was, so nobody who liked it loses it.
 */
export const SIDEBAR_WIDTH_MAX = 420

const SIDEBAR_KEY = 'agent-commander.sidebar'
const SIDEBAR_WIDTH_KEY = 'agent-commander.sidebar-width'

export function loadSidebar(): SidebarState {
  return read(SIDEBAR_KEY) === 'collapsed' ? 'collapsed' : 'expanded'
}

export function saveSidebar(state: SidebarState): void {
  write(SIDEBAR_KEY, state)
}

export function clampSidebarWidth(width: number): number {
  if (!Number.isFinite(width)) return SIDEBAR_WIDTH_DEFAULT
  return Math.min(SIDEBAR_WIDTH_MAX, Math.max(SIDEBAR_WIDTH_MIN, Math.round(width)))
}

/*
 * A stored width is clamped on the way out as well as in. The bounds can move
 * between releases, and a value written by an older one must not be honoured
 * past them — nor must a hand-edited or half-written entry, which is why a
 * non-number falls back to the default rather than to zero.
 */
export function loadSidebarWidth(): number {
  const stored = read(SIDEBAR_WIDTH_KEY)
  if (stored === null) return SIDEBAR_WIDTH_DEFAULT
  const parsed = Number(stored)
  return Number.isFinite(parsed) && parsed > 0 ? clampSidebarWidth(parsed) : SIDEBAR_WIDTH_DEFAULT
}

export function saveSidebarWidth(width: number): void {
  write(SIDEBAR_WIDTH_KEY, String(clampSidebarWidth(width)))
}

/*
 * The last fleet this browser saw, for the next cold start.
 *
 * What is kept is the fleet's *shape* — which sessions, what state, where —
 * so a phone whose page iOS evicted can paint that at once, captioned as a
 * memory, while the tunnel re-forms. What is not kept is anything an agent
 * said: the activity line is a tool call with its arguments, the last prompt
 * is the user's words, the title is made from the conversation, and the goal
 * is an instruction. The token left browser storage because a phone's history
 * and screenshots are where such storage ends up (INV-3), and a conversation
 * is what the token protects. The allow-list below is the whole of what may
 * be written; a new `Agent` field is out until it is named here.
 *
 * An empty fleet is forgotten rather than saved: the confirmed-empty screen is
 * a claim the server made once, not one this browser may repeat from memory
 * (INV-11).
 */
const FLEET_KEY = 'agent-commander.fleet'

export interface FleetSnapshot {
  at: number
  agents: Agent[]
}

const REMEMBERED: readonly (keyof Agent)[] = [
  'sessionId',
  'pid',
  'name',
  'cwd',
  'folder',
  'status',
  'statusInferred',
  'waitingFor',
  'agentKind',
  'kind',
  'startedAt',
  'lastActivityAt',
  'paneId',
  'gitBranch',
  'derivedName',
]

function remembered(agent: Agent): Agent {
  const kept: Partial<Agent> = {}
  for (const key of REMEMBERED) {
    if (agent[key] !== undefined) (kept as Record<string, unknown>)[key] = agent[key]
  }
  return kept as Agent
}

export function saveFleetSnapshot(agents: Agent[], savedAt: number): void {
  if (agents.length === 0) {
    try {
      localStorage.removeItem(FLEET_KEY)
    } catch {
      /* not fatal */
    }
    return
  }
  write(FLEET_KEY, JSON.stringify({ at: savedAt, agents: agents.map(remembered) }))
}

function isSnapshot(value: unknown): value is FleetSnapshot {
  if (typeof value !== 'object' || value === null) return false
  const snap = value as { at?: unknown; agents?: unknown }
  return (
    typeof snap.at === 'number' &&
    Array.isArray(snap.agents) &&
    snap.agents.length > 0 &&
    snap.agents.every((a) => typeof a === 'object' && a !== null && typeof a.sessionId === 'string')
  )
}

export function loadFleetSnapshot(): FleetSnapshot | null {
  const raw = read(FLEET_KEY)
  if (raw === null) return null
  try {
    const parsed: unknown = JSON.parse(raw)
    return isSnapshot(parsed) ? parsed : null
  } catch {
    return null
  }
}
