/**
 * Colour scheme and theme, end to end: that a choice repaints the real
 * document, that the two axes stay independent of each other, and that both
 * survive a reload.
 *
 * Vitest already covers `prefs.ts`, but jsdom has no cascade. It will happily
 * report that `data-scheme` was set while nothing about the page's colours has
 * moved — which is exactly the bug shape worth catching, since the attribute is
 * only ever a means to the repaint. Only a browser with the stylesheet loaded
 * can say a scheme was *applied* rather than merely recorded.
 *
 * No hex value is written down here on purpose. Every colour in `tokens.css` is
 * generated by `scripts/gen-themes.py` and re-measured by
 * `scripts/audit-contrast.py`; a spec that pinned the values would turn each
 * regeneration into a wall of failures that say nothing. These assert the
 * relationships the generator must preserve instead — changed, distinct,
 * absent — and leave the values to the tools that own them.
 */
import { expect, test, type Page } from '@playwright/test'
import { SCHEMES } from '../src/web/lib/prefs.ts'
import { openFleet } from './helpers.ts'

/**
 * The colour the page is actually painted.
 *
 * `body { background: var(--bg) }`, so this resolves the whole chain — the
 * attribute on <html>, the selector that matched it, and the custom property it
 * set — down to the one value a user could point at on screen.
 */
const bodyBg = (page: Page): Promise<string> =>
  page.evaluate(() => getComputedStyle(document.body).backgroundColor)

/** Rough brightness, for "is this the dark one" — not a contrast measurement. */
function brightness(colour: string): number {
  const parts = colour.match(/[\d.]+/g)
  expect(parts, `expected a parseable colour, got ${colour}`).not.toBeNull()
  // Red, green and blue summed, alpha ignored. Enough to order two colours by
  // lightness, which is the only question asked of it.
  return (parts as string[]).slice(0, 3).reduce((sum, part) => sum + Number(part), 0)
}

/** A colour the browser could resolve, rather than an empty string. */
function expectPainted(colour: string): void {
  expect(colour).toMatch(/^rgba?\(/)
}

async function openSettings(page: Page): Promise<void> {
  await page.getByTestId('settings-button').click()
  await expect(page.getByTestId('settings-menu')).toBeVisible()
}

/**
 * Pick a scheme, from wherever the menu currently is.
 *
 * The scheme buttons deliberately leave the menu open so palettes can be
 * compared without four clicks apiece, so re-opening is conditional rather than
 * unconditional — clicking the settings button when the menu is already open
 * would close it, and the next click would land on nothing.
 */
async function chooseScheme(page: Page, scheme: string): Promise<void> {
  const menu = page.getByTestId('settings-menu')
  if (!(await menu.isVisible())) await openSettings(page)
  await page.getByTestId(`scheme-${scheme}`).click()
}

/** Pick a theme. Unlike a scheme, this closes the menu behind it. */
async function chooseTheme(page: Page, theme: string): Promise<void> {
  const menu = page.getByTestId('settings-menu')
  if (!(await menu.isVisible())) await openSettings(page)
  await page.getByTestId(`theme-${theme}`).click()
  await expect(menu).toBeHidden()
}

/**
 * Wait for the document to be painted in something other than `before`.
 *
 * Polled rather than slept through: the repaint is a React state change
 * followed by a style recalculation, and how long that takes is not a number
 * worth guessing at.
 */
async function bgAfterChangeFrom(page: Page, before: string): Promise<string> {
  await expect.poll(() => bodyBg(page)).not.toBe(before)
  const after = await bodyBg(page)
  expectPainted(after)
  return after
}

test.describe('colour scheme and theme', () => {
  test('picking a scheme repaints the document, not just the attribute', async ({ page }) => {
    await openFleet(page)
    const before = await bodyBg(page)
    expectPainted(before)

    await chooseScheme(page, 'ember')

    // The point of the whole feature. An attribute that landed without the
    // stylesheet answering it would pass every unit test and change nothing a
    // user can see.
    const after = await bgAfterChangeFrom(page, before)
    expect(after).not.toBe(before)
  })

  test('the chosen scheme is an attribute, and the default is its absence', async ({ page }) => {
    await openFleet(page)
    const html = page.locator('html')

    // Graphite is written as the bare `:root`, so a fresh document carries no
    // scheme attribute at all — that is what makes an unstyled-by-preference
    // document still complete.
    await expect(html).not.toHaveAttribute('data-scheme')

    await chooseScheme(page, 'nordic')
    await expect(html).toHaveAttribute('data-scheme', 'nordic')

    /*
     * Returning to the default has to *remove* the attribute rather than write
     * `data-scheme="graphite"`. The CSS has no selector for that value, so a
     * literal graphite would silently leave nordic's palette on screen while
     * the menu claimed graphite was selected.
     */
    await chooseScheme(page, 'graphite')
    await expect(html).not.toHaveAttribute('data-scheme')
  })

  test('the scheme and the theme both survive a reload', async ({ page }) => {
    await openFleet(page)
    await chooseScheme(page, 'mauve')
    await chooseTheme(page, 'dark')

    const chosen = await bodyBg(page)
    expectPainted(chosen)

    await page.reload()
    await expect(page.getByTestId('agent-card').first()).toBeVisible()

    /*
     * Both preferences live in localStorage and are applied on boot. The pair
     * matters more than either alone: an earlier shape of this code restored
     * the theme and forgot the scheme, which reads as the app having lost the
     * palette rather than as a bug in one of two independent stores.
     */
    await expect(page.locator('html')).toHaveAttribute('data-scheme', 'mauve')
    await expect(page.locator('html')).toHaveAttribute('data-theme', 'dark')
    await expect.poll(() => bodyBg(page)).toBe(chosen)
  })

  test('the theme changes within the scheme rather than instead of it', async ({ page }) => {
    await openFleet(page)
    await chooseScheme(page, 'solar')
    await expect(page.locator('html')).toHaveAttribute('data-scheme', 'solar')

    await chooseTheme(page, 'light')
    const light = await bodyBg(page)
    expectPainted(light)
    await expect(page.locator('html')).toHaveAttribute('data-scheme', 'solar')

    await chooseTheme(page, 'dark')
    const dark = await bgAfterChangeFrom(page, light)

    // Two axes, not one list of ten. Switching light to dark must move the
    // colour and leave the palette family exactly where it was.
    await expect(page.locator('html')).toHaveAttribute('data-scheme', 'solar')
    expect(brightness(dark)).toBeLessThan(brightness(light))
  })

  test('every scheme in the menu paints a distinct background', async ({ page }) => {
    await openFleet(page)
    // Pinned to a single theme so the five readings differ by palette alone;
    // comparing across light and dark would prove nothing about the schemes.
    await chooseTheme(page, 'dark')

    const painted = new Map<string, string>()
    for (const scheme of SCHEMES) {
      await chooseScheme(page, scheme)
      const expected = scheme === 'graphite' ? null : scheme
      if (expected === null) await expect(page.locator('html')).not.toHaveAttribute('data-scheme')
      else await expect(page.locator('html')).toHaveAttribute('data-scheme', expected)

      const colour = await bodyBg(page)
      expectPainted(colour)
      painted.set(scheme, colour)
    }

    /*
     * Five names in a menu that resolve to fewer than five colours is the
     * failure this catches: a scheme whose block never made it into the
     * generated stylesheet falls back to the bare `:root` and looks, to
     * everything except the eye, like it applied.
     */
    expect(new Set(painted.values()).size, `duplicate palettes: ${JSON.stringify([...painted])}`).toBe(
      SCHEMES.length,
    )
  })

  test('with the theme on system, the system preference is what decides', async ({ page }) => {
    await page.emulateMedia({ colorScheme: 'light' })
    await openFleet(page)

    // "System" is the absence of `data-theme`, which is what lets the media
    // query in `tokens.css` be the thing that answers. A default that wrote
    // `data-theme="light"` would pin every user to whatever the browser
    // happened to prefer the first time they loaded the page.
    await expect(page.locator('html')).not.toHaveAttribute('data-theme')
    const light = await bodyBg(page)
    expectPainted(light)

    await page.emulateMedia({ colorScheme: 'dark' })
    const dark = await bgAfterChangeFrom(page, light)

    await expect(page.locator('html')).not.toHaveAttribute('data-theme')
    expect(brightness(dark)).toBeLessThan(brightness(light))

    // And back, because a one-way follow is indistinguishable from the page
    // having simply been rebuilt dark at some point.
    await page.emulateMedia({ colorScheme: 'light' })
    await expect.poll(() => bodyBg(page)).toBe(light)
  })

  test('text is still painted against the page after a scheme change', async ({ page }) => {
    await openFleet(page)
    await chooseScheme(page, 'ember')
    await expect(page.locator('html')).toHaveAttribute('data-scheme', 'ember')

    const name = page.getByTestId('agent-name').first()
    await expect(name).toBeVisible()
    const [colour, background] = await Promise.all([
      name.evaluate((el) => getComputedStyle(el).color),
      bodyBg(page),
    ])

    /*
     * A sanity check, not a contrast check. `scripts/audit-contrast.py` is the
     * real gate — it measures every token pair in every scheme against WCAG,
     * and re-deriving any of that here would mean two implementations of the
     * same maths disagreeing over rounding. What this catches is the cruder
     * failure it would be embarrassing to ship: a scheme that defined `--bg`
     * and left `--text` unset, so the page renders as text-coloured-on-itself.
     */
    expectPainted(colour)
    expect(colour).not.toMatch(/,\s*0\s*\)$/)
    expect(colour).not.toBe(background)
  })
})
