/*
 * Wire types shared by the server and the browser client.
 *
 * GENERATED from rust/src/types.rs by `npm run gen:types` — do not edit.
 * `types::tests::the_checked_in_wire_contract_is_current` fails when this
 * file and the Rust disagree. The doc comments are the Rust doc comments;
 * change them there.
 */

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One Claude Code session, as presented to the UI.
 */
export type Agent = { sessionId: string, pid: number, name: string, cwd: string, 
/**
 * Basename of cwd, precomputed for the card header.
 */
folder: string, status: AgentStatus, 
/**
 * The status above was derived by this app rather than reported by the agent.
 *
 * INV-11: the dashboard never asserts more than it knows. A Claude session
 * says "waiting, dialog open" about itself; a tmux-discovered agent only
 * ever shows whether its pane has produced output lately, which is a far
 * weaker claim wearing the same word.
 */
statusInferred?: boolean, 
/**
 * Why the agent is blocked, e.g. "dialog open". Only when status is waiting.
 */
waitingFor?: string, 
/**
 * Which agent CLI this is — see `agent_kinds.rs`.
 *
 * Not optional, so every construction site has to say: a silent default
 * here reaches a capability lookup and quietly denies everything. Distinct
 * from `kind` below, which is Claude Code's own word for the sort of
 * session it is and means nothing elsewhere.
 */
agentKind: string, kind: string, startedAt: number, version?: string, gitBranch?: string, 
/**
 * tmux pane id (e.g. "%77"). Absent means the agent cannot be attached to.
 */
paneId?: string, 
/**
 * tmux session name, display only — never attached to (INV-1).
 */
tmuxSession?: string, attachBlockedReason?: string, activity?: string, lastActivityAt?: number, tokens?: number, subagents?: number, 
/**
 * Handed work to a subagent and doing nothing itself until it returns.
 */
delegating?: boolean, aiTitle?: string, lastPrompt?: string, derivedName?: boolean, permissionMode?: string, model?: string, goal?: GoalState, };

export type AgentStatus = "busy" | "idle" | "waiting" | "unknown";

/**
 * One agent's delegates. `children` is empty for an agent that never delegated.
 */
export type AgentTree = { sessionId: string, children: Array<SubagentNode>, 
/**
 * This app cannot tell whether this agent has delegated at all.
 *
 * True for a CLI that keeps no transcript: the evidence lives in files it
 * does not write, so an empty tree here is absence of evidence rather than
 * evidence of absence, and must not read as "delegated nothing".
 */
unknown?: boolean, };

export type ChangedRow = { row: number, text: string, };

export type ClientMessage = { "type": "focus", sessionId: string | null, } | { "type": "attach", sessionId: string, on: boolean, } | { "type": "paste", sessionId: string, text: string, submit: boolean, seq?: number, } | { "type": "key", sessionId: string, key: string, confirmed?: boolean, } | { "type": "answer", sessionId: string, promptId: string, choice: number, };

/**
 * `{ ok: true, detail? } | { ok: false, error }`
 */
export type ControlResponse = { ok: true, detail?: string, } | { ok: false, error: string, };

export type DirEntryDto = { name: string, path: string, hidden: boolean, };

export type DirListing = { path: string, parent: string | null, root: string, entries: Array<DirEntryDto>, };

/**
 * Structured error conditions a client may branch on.
 */
export type ErrorKind = "pane-exited";

/**
 * The whole fleet's delegation graph, as served by `GET /api/tree`.
 */
export type FleetTree = { trees: Array<AgentTree>, };

/**
 * A rendered snapshot of a tmux pane.
 */
export type Frame = { sessionId: string, cols: number, rows: number, cursorX: number, cursorY: number, 
/**
 * Full frame: every line, padded to `rows`. Sent on first paint and resync.
 */
lines?: Array<string>, 
/**
 * Sparse update: only the rows that changed since the last frame.
 */
changed?: Array<ChangedRow>, };

/**
 * A Claude Code session goal, as recorded by `/goal` in the transcript.
 */
export type GoalState = { condition: string, 
/**
 * True once the evaluator confirmed it. A met goal is finished, not running.
 */
met: boolean, at: number, reason?: string, 
/**
 * True when this is the set-record, so nothing has evaluated it yet.
 */
fresh?: boolean, };

export type NewAgentRequest = { cwd: string, name?: string, model?: string, permissionMode?: string, };

/**
 * `{ ok: true, tmuxSession, cwd } | { ok: false, error }`
 */
export type NewAgentResponse = { ok: true, tmuxSession: string, cwd: string, } | { ok: false, error: string, };

/**
 * Which compaction notice a `Notice` event is reporting.
 */
export type NoticeKind = "compacted" | "compactedAuto";

/**
 * A question the agent is waiting on, read out of its own transcript.
 *
 * Claude Code flushes a tool call before the dialog it raises is answered, so
 * an `AskUserQuestion` still waiting for a reply is on disk in full — question,
 * options, and whether it takes more than one. That is the only reason this
 * app may name an option at all: it is *read*, never inferred from the screen
 * (INV-16).
 *
 * The other two blocked shapes are deliberately thinner. `ExitPlanMode` writes
 * its plan but not the three approval choices, which the CLI composes; a tool
 * permission request writes the tool and its input but not the numbered list.
 * For those `options` stays empty and the interface offers keys rather than
 * labels it would have had to invent.
 */
export type PendingPrompt = { 
/**
 * The tool that raised it — `AskUserQuestion`, `ExitPlanMode`, or another.
 */
tool: string, 
/**
 * The question, where the transcript states one.
 */
question?: string, 
/**
 * Only ever what the transcript named. Absent means "not knowable here".
 */
options?: Array<PromptOption>, 
/**
 * True when the picker takes several answers, so one digit cannot finish it.
 */
multiSelect?: boolean, 
/**
 * How many questions this one call asks, when it asks more than one.
 */
moreQuestions?: number, 
/**
 * Reference text: the plan under review, or the command being asked about.
 */
detail?: string, 
/**
 * Identity of *this* question, for binding an answer to it (INV-2).
 *
 * Derived from the content rather than stored anywhere: the transcript
 * issues no id, and a counter would not survive the server restarting
 * under a browser that stayed open. Filled by `with_id` on the way out;
 * empty on a prompt that has not been sent.
 */
id?: string, };

/**
 * One choice in a prompt the agent is blocked on.
 */
export type PromptOption = { label: string, description?: string, };

/**
 * Account-level subscription usage, bridged out of Claude Code's statusLine.
 */
export type RateLimits = { fiveHour?: UsageWindow, sevenDay?: UsageWindow, 
/**
 * Epoch ms the bridge last wrote. The UI dims the meters once this is old.
 */
at: number, };

/**
 * Facts about the host machine, used by the help page.
 */
export type ServerEnv = { tailscale: TailscaleEnv | null, 
/**
 * False when no tmux server is reachable, which disables attach and spawning.
 */
tmux: boolean, port: number, platform: string, 
/**
 * The version of the code that is answering, not of anything asking.
 *
 * Compiled in from `CARGO_PKG_VERSION`, so it cannot drift from the binary
 * the way a string read off disk could — and `the_two_manifests_agree`
 * keeps that in step with the npm package the binary ships inside.
 */
version: string, };

export type ServerMessage = { "type": "fleet", agents: Array<Agent>, mock: boolean, } | { "type": "limits", limits: RateLimits | null, } | { "type": "timeline", sessionId: string, events: Array<TimelineEvent>, reset: boolean, 
/**
 * What this agent is blocked on, when its transcript says.
 *
 * Sent with the conversation rather than on the fleet frame: the fleet
 * goes out for every agent many times a minute, and this is only ever
 * wanted for the one being read.
 */
prompt?: PendingPrompt, } | { "type": "frame", frame: Frame, } | { "type": "paste-ack", sessionId: string, seq: number, } | { "type": "error", sessionId?: string, message: string, 
/**
 * `kind` names the condition; `message` is only how to say it. The
 * pane-exit case is the one state a viewer must react to
 * structurally, because INV-1 means there is no pty to report it.
 */
kind?: ErrorKind, };

/**
 * One delegate in an agent's tree, and everything below it.
 */
export type SubagentNode = { 
/**
 * Claude Code's own id for the delegate; the transcript is named after it.
 */
agentId: string, 
/**
 * The subagent type, e.g. `general-purpose`, or a forked skill's name.
 */
agentType: string, 
/**
 * The one-line brief the parent gave it.
 */
description: string, 
/**
 * 1 for a delegate of the session itself, 2 for a delegate of a delegate.
 */
depth: number, parentAgentId?: string, 
/**
 * When its transcript was last written to.
 */
lastWriteAt: number, 
/**
 * Transcript size. A coarse "how much work", never a percentage.
 */
bytes: number, 
/**
 * Tool calls recorded in its transcript, and the span it worked over.
 *
 * What it *did*, as against `state`, which is what became of it. Both are
 * needed because `state` is almost always `quiet` — the honest answer, and
 * an uninformative one on its own (INV-13). Absent when the transcript
 * could not be read or is too large to keep re-reading; a node then
 * renders without them rather than with a zero, which would claim it did
 * nothing.
 */
calls?: number, workedMs?: number, state: SubagentState, 
/**
 * The state was worked out here rather than reported (INV-11). Set on
 * `active`, which is a guess from a recent write and a busy parent, and
 * never on `done`, which is only ever claimed on evidence.
 */
stateInferred?: boolean, 
/**
 * The user stopped it. Evidence of an ending, so the state is `done`.
 */
stoppedByUser?: boolean, 
/**
 * Its parent id named a delegate that is not on disk, so it was raised to
 * the top of the tree rather than dropped with everything under it.
 */
reparented?: boolean, children: Array<SubagentNode>, };

/**
 * What a delegate is doing, and how much of that this app actually knows.
 */
export type SubagentState = "active" | "quiet" | "done";

export type TailscaleEnv = { cliPath: string, dnsName: string, ip: string, running: boolean, };

export type TimelineEvent = { id: string, at: number, kind: TimelineKind, 
/**
 * Primary line of text.
 */
text: string, 
/**
 * Tool name, for kind == Tool.
 */
tool?: string, 
/**
 * True when this event came from a subagent sidechain.
 */
sidechain?: boolean, 
/**
 * For `kind == Notice`: which notice this is, so the client names it in
 * the reader's language rather than showing a sentence the server wrote.
 */
notice?: NoticeKind, 
/**
 * Context tokens either side of a compaction, for the notice above.
 */
tokensBefore?: number, tokensAfter?: number, };

export type TimelineKind = "user" | "assistant" | "tool" | "subagent" | "notice";

/**
 * One quota window, as a percentage used and when it refills.
 */
export type UsageWindow = { 
/**
 * 0-100.
 */
pct: number, resetsAt?: number, };

/**
 * Control keys the server will forward. Anything else is rejected (INV-2).
 * The digits are how a numbered choice is answered.
 */
export const ALLOWED_KEYS = ["Enter", "Escape", "Tab", "BSpace", "Space", "Up", "Down", "Left", "Right", "Home", "End", "PageUp", "PageDown", "C-c", "C-d", "C-o", "C-r", "C-u", "1", "2", "3", "4", "5", "6", "7", "8", "9"] as const

/** Keys that can destroy work, so the UI must confirm before sending (INV-6). */
export const DESTRUCTIVE_KEYS = new Set(["C-c", "C-d", "Escape"])

/** Model aliases the CLI accepts, and the only ones this app will pass on. */
export const MODEL_ALIASES = ["default", "opus", "sonnet", "haiku", "fable", "opusplan"] as const

/** Permission modes in the order Shift+Tab cycles them. */
export const MODE_CYCLE = ["default", "acceptEdits", "plan", "bypassPermissions", "auto"] as const

/** Modes settable at spawn time. `dontAsk` is reachable by flag but never cycles. */
export const SPAWN_MODES = ["default", "acceptEdits", "plan", "bypassPermissions", "auto", "dontAsk"] as const
